keys:
  - &admin age1evwgphns0ys2mu78mmtal32wghrswpddpk7ryv2kp5xwk8t5pujsglu3eq
  - &nexus age12h6h4q6mr9djnj3lmwkv5hthexghx0emj75xnt8hv76hmn7z9vysne9uyz
creation_rules:
  - path_regex: (^|/)secrets/nexus/(hostkey|console-admin)\.yaml$
    key_groups:
      - age:
        - *admin
  - path_regex: (^|/)secrets/nexus/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin
        - *nexus
