{ config, lib, pkgs, flakeRoot, ... }:

let
  username = config.myConfig.modules.users.username;
in
{
  options.myConfig.modules.bash.enable = lib.mkEnableOption "Bash shell configuration";
  config = lib.mkIf config.myConfig.modules.bash.enable {
    environment.etc.bash_logout.text = lib.mkForce ''
      # /etc/bash_logout: generated by Firn.

      # A login command may enable nounset before Bash sources this file.
      if [ -n "''${__ETC_BASHLOGOUT_SOURCED:-}" ] || [ -n "''${NOSYSBASHLOGOUT:-}" ]; then
        return 0
      fi
      __ETC_BASHLOGOUT_SOURCED=1

      ${config.programs.bash.logout}

      if test -f /etc/bash_logout.local; then
        . /etc/bash_logout.local
      fi

    '';
    programs.bash.completion.enable = true;
    environment.systemPackages = with pkgs; [ fzf ];
    home-manager.users.${username} = ({ config, ... }: {
      home.file.".local/bin".source = "${flakeRoot}/dotfiles/bin";
      programs.bash = {
        enable = true;
        shellAliases = {
          dsp = "--dangerously-skip-permissions";
          du = "dust";
          ls = "eza";
          ps = "procs";
          v = "nvim";
          e = "emacsclient -n -c -a emacs";
          etui = "emacsclient -t -a emacs";
          gits = "git status";
          gitd = "git diff";
          gitdc = "git diff --cached";
          gita = "git add -v . && git status";
          gitp = "git push";
        };
        historyControl = [ "ignoredups" "erasedups" ];
        historySize = 100000;
        historyFileSize = 100000;
        shellOptions = [
          "histappend"
          "checkwinsize"
          "cmdhist"
          "globstar"
          "autocd"
          "cdspell"
          "dirspell"
        ];
        bashrcExtra = ''

          # Ensure ~/.local/bin (where dotfiles/bin is symlinked) is on PATH.
          case ":$PATH:" in
            *":$HOME/.local/bin:"*) ;;
            *) export PATH="$HOME/.local/bin:$PATH" ;;
          esac

          # Readline-dependent setup. Skip cleanly on bash builds without
          # readline (pkgs.bash in nix dev shells) — `set -o vi`, `bind`,
          # `complete`, and the fzf bindings all need readline. The cd-to-home
          # block below is intentionally outside this gate.
          if [[ $- == *i* ]] && type bind >/dev/null 2>&1; then
            # vi-mode (use 'set -o emacs' to switch back temporarily)
            set -o vi

            # Ctrl+L → clear screen, in every keymap. vi-mode doesn't
            # bind this by default (it's an emacs-mode default), so
            # set it explicitly in both vi-insert and vi-command.
            bind -m emacs       '"\C-l": clear-screen'
            bind -m vi-insert   '"\C-l": clear-screen'
            bind -m vi-command  '"\C-l": clear-screen'

            # fzf integration (Ctrl-R for fuzzy history, Alt-C for cd)
            if command -v fzf-share >/dev/null 2>&1; then
              source "$(fzf-share)/key-bindings.bash"
              source "$(fzf-share)/completion.bash"
            fi
          fi

          # Change to home dir on interactive start (skip in Emacs vterm).
          # No readline dep, runs even in stripped bash.
          if [ -z "$INSIDE_EMACS" ] && [ -t 0 ]; then
            case "$PWD" in
              "$HOME"*) ;;
              *) cd "$HOME" ;;
            esac
          fi

        '';
      };
    });
  };
}
